### ISSUE TITLE
誤記: P21 インストールされているソフトウェアのURL

### ISSUE THREAD

**Issue by macneko-ayu** [github-actions-up-and-running/contact#10]
誤記：https://help.github.com/en/actions/reference/software-installed-ongithub-hosted-runners
正解：https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners

**Comment by miyajan** [comment]
@macneko-ayu 
ご報告ありがとうございます！
ただ、手元ではすでに正解の URL になっており、誤記が確認できませんでした。
macneko-ayu さんが誤記を確認されたのは、PDF 版と紙書籍版のどちらか教えてもらってもよろしいでしょうか？
また、書籍の最後に乗ってるバージョン番号（e.g. 1.0.0）も合わせて教えてもらえると助かります。
よろしくお願いいたします！

**Comment by macneko-ayu** [comment]
情報が足りなくてすみませんでした。
v1.0.2のPDF版です。
念の為、BoothでPDFをダウンロードし直したのですが、同じバージョンでした

**Comment by miyajan** [comment]
@macneko-ayu 
情報ありがとうございます！
ただ、手元では v1.0.2 でも誤記を確認できず、おそらく PDF ビューアーソフトの違いによるものなのではと思っています。
もし可能であれば、PDF ビューアーになにを使ってるか教えてもらうことはできますか？
また、もし可能であれば chrome で PDF を開いて同じ問題が発生するかご確認をお願いできないでしょうか？
ご確認のお願いばかりになってしまい大変申し訳ありません🙇‍♂️

**Comment by macneko-ayu** [comment]
原因がわかりました。
PDFをKindleに取り込んで読んでいるのですが、Kindle上のURLリンクをタップするとなぜかハイフンが欠落して遷移ができず、URLが誤っていると勘違いしておりました…。
descriptionに記載したURLがブラウザのアドレス欄に表示されていたものですが、PDF上の表記は問題なかったです。
ご迷惑おかけしました🙇

**Comment by miyajan** [comment]
@macneko-ayu 
おお、原因がわかってよかったです！
ご確認いただきありがとうございました！
